<?php

/**
 * @file
 * Add a handler for Panopto.com videos to Video Embed Field.
 *
 * @see video_embed_field.api.php for more documentation
 */

define('VIDEO_EMBED_PANOPTO_DEFAULT_WIDTH', '640');
define('VIDEO_EMBED_PANOPTO_DEFAULT_HEIGHT', '480');

/**
 * Implements hook_theme().
 */
function video_embed_panopto_theme($existing, $type, $theme, $path) {
  return array(
    'video_embed_panopto' => array(
      'template' => 'video_embed_panopto',
      'path' => drupal_get_path('module', 'video_embed_panopto') . '/templates',
      'arguments' => array(
        'url' => NULL,
        'width' => NULL,
        'height' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_video_embed_handler_info().
 */
function video_embed_panopto_video_embed_handler_info() {
  $handlers = array();
  $handlers['panopto'] = array(
    'title' => 'Panopto Video',
    'function' => 'video_embed_panopto_handle_video',
    'thumbnail_function' => 'video_embed_panopto_handle_thumbnail',
    'form' => 'video_embed_panopto_form',
    // As panopto uses client-based subdomains you will need to implement
    // hook_video_embed_handler_info_alter() with your own white-listed domain.
    'domains' => array(
      'panopto.eu',
      'panopto.com',
    ),
    'defaults' => array(
      'width' => VIDEO_EMBED_PANOPTO_DEFAULT_WIDTH,
      'height' => VIDEO_EMBED_PANOPTO_DEFAULT_HEIGHT,
    ),
  );
  return $handlers;
}

/**
 * Builds the configuration form for the video player.
 *
 * @param array $defaults
 *   The form default values.
 *
 * @return array
 *   The provider settings form array.
 */
function video_embed_panopto_form(array $defaults) {
  $form = array();
  $form['width'] = array(
    '#type' => 'textfield',
    '#title' => t('Player Width'),
    '#description' => t('The width of the player.'),
    '#default_value' => $defaults['width'],
  );
  $form['height'] = array(
    '#type' => 'textfield',
    '#title' => t('Player Height'),
    '#description' => t('The height of the player.'),
    '#default_value' => $defaults['height'],
  );
  $form['autoplay'] = array(
    '#type' => 'checkbox',
    '#title' => t('Autoplay'),
    '#description' => t('Play the video immediately.'),
    '#default_value' => $defaults['autoplay'],
  );
  return $form;
}

/**
 * Validates the form elements for the Panopto video configuration form.
 *
 * @param array $element
 *   The form element to validate.
 * @param array $form_state
 *   The form to validate state.
 * @param array $form
 *   The form to validate structure.
 */
function video_embed_panopto_form_validate(array $element, array &$form_state, array $form) {
  video_embed_field_validate_dimensions($element);
}

/**
 * Adds panopto specific settings into VEF settings form.
 *
 * Implements hook_form_FORM_ID_alter().
 */
function video_embed_panopto_form_video_embed_field_settings_form_alter(&$form, &$form_state, $form_id) {
  $form['video_embed_field_panopto_client_domains'] = array(
    '#type' => 'textarea',
    '#title' => t('Panopto client domains'),
    '#description' => t('Panopto does not use an unique host, but client-specific subdomains. For that reason we need to whitelist client domains. Add one domain per line, e.g.:<br> <em>myclientname.cloud.panopto.eu</em><br><em>mysecondclient.cloud.panopto.eu</em>'),
    '#default_value' => variable_get('video_embed_field_panopto_client_domains', ''),
  );
  $form['#submit'][] = '_video_embed_panopto_form_video_embed_field_settings_clear_cache';
}

/**
 * Clears the video_embed_field_handlers cache
 *
 * Necessary to register our new client domains.
 * @see video_embed_panopto_video_embed_handler_info_alter()
 *
 * @param array $form
 *   Form elements that comprise the form.
 * @param array $form_state
 *  Current state of the form.
 */
function _video_embed_panopto_form_video_embed_field_settings_clear_cache(array $form, array &$form_state) {
  cache_clear_all('video_embed_field_handlers', 'cache');
}

/**
 * Injects the whitelisted panopto client domains into the handler.
 *
 * When not whitelisting domain the field validation will return a
 * `This video provider is not currently supported` error.
 *
 * Implements hook_video_embed_handler_info_alter().
 */
function video_embed_panopto_video_embed_handler_info_alter(array &$info) {
  if ($client_domains_value = variable_get('video_embed_field_panopto_client_domains', '')) {
    $client_domains = preg_split('/(\r\n?|\n)/', $client_domains_value);
    if (!empty($client_domains)) {
      $info['panopto']['domains'] = array_merge($info['panopto']['domains'], $client_domains);
    }
  }
}

/**
 * Video handler create the embedded video output.
 *
 * @param $url
 *   Panopto video or embed url.
 * @param array $settings
 *   An associative array of this handlers settings, from the settings form.
 *
 * @return array|string
 *   The embed code for the video.
 */
function video_embed_panopto_handle_video($url, array $settings) {
  $output = '';
  $video_details = _video_embed_panopto_get_video_details($url);

  if ($video_details) {
    // The module currently supports version 1 only.
    $video_details['version'] = 1;
    $video_details['autoplay'] = $settings['autoplay'] ? 'true' : 'false';

    // Theme the embedding element.
    $embed = theme('video_embed_panopto', array(
      'url' => '\\\\' . $video_details['client_id'] . '.' . $video_details['server'] . '/Panopto/Pages/Viewer.aspx?id=' . $video_details['video_id'] . '&v=' . $video_details['version'] . '&autoplay=' . $video_details['autoplay'],
      'width' => $settings['width'],
      'height' => $settings['height'],
    ));

    // Return a render array.
    $video = array(
      '#markup' => $embed,
    );
    $output = $video;
  }
  else {
    drupal_set_message(t('Error with getting id of the video.'), 'error');
  }

  // Return an empty string if there is no id, so we don't have broken embeds.
  return $output;
}

/**
 * Retrieves the thumbnail for the Panopto video.
 *
 * @param string $url
 *   Panopto video or embed url.
 *
 * @return array
 *   an array with the keys:
 *     'id' => an id for the video which is unique to your provider
 *     'url' => the url to retrieve the thumbnail from
 */
function video_embed_panopto_handle_thumbnail($url) {
  $video_details = _video_embed_panopto_get_video_details($url);
  $thumbnail = 'https://' . $video_details['client_id'] . '.' . $video_details['server'] . '/Panopto/PublicAPI/SessionPreviewImage?id=' . $video_details['video_id'];
  return array(
    'id' => $video_details['video_id'],
    'url' => $thumbnail,
  );
}

/**
 * Helper function to extract video information from panopto URLs.
 *
 * @param string $url
 *   Panopto video or embed url.
 *
 * @return array|bool
 *   Video details of the video or FALSE if there is no match.
 */
function _video_embed_panopto_get_video_details($url) {
  $matches = array();
  $patterns = array(
    '@.*//(.*).(hosted.panopto.com|cloud.panopto.eu)/Panopto/Pages/Viewer\.aspx\?id\=([^"\&]+)@i',
    '@.*//(.*).(hosted.panopto.com|cloud.panopto.eu)/Panopto/Pages/Embed\.aspx\?id\=([^"\&]+)@i',
  );
  foreach ($patterns as $pattern) {
    preg_match($pattern, $url, $matches);
    if (!empty($matches[1]) && !empty($matches[2]) && !empty($matches[3])) {
      return array(
        'client_id' => $matches[1],
        'server' => $matches[2],
        'video_id' => $matches[3],
      );
    }
  }
  return FALSE;
}
